### PR TITLE
Merge base:rewrite-from-scratch <- fork:rewrite-from-scratch

### PR DESCRIPTION
**Pull request by unholy-codeism**
~~That's all.~~

This PR introduces a lot of stuff but it stills needs:
- All minigames that aren't `crew` (won't be done any time soon as I still need to add the bases)
- A global list of commands from `&help` (although, the contents of &help <command> are pretty precise in my opinion - even so they're still incomplete)
- A good way to check for required arguments other than a list of validValues (I have some work done on that, it just uses a function)
- ~~Probably another thing I've forgotten.~~ nvm all clear

### CODE REVIEW

**Comment by unholy-codeism** [comment]
Any objections?

**Comment by Felix-44** [comment]
not sure what this pr does but sure go ahead

**Comment by unholy-codeism** [comment]
> not sure what this pr does but sure go ahead

:skull: did i not mention what this branch was for 
also i'm not gonna merge until i've added what i mentioned in the top comment

**Comment by Felix-44** [comment]
but then why is this not a draft-

**Comment by unholy-codeism** [comment]
to merge faster
it's not like it'd be so bad if it got merged right now anyway

**Comment by unholy-codeism** [comment]
Ok, this is clear for merge as it does everything I still need it to do
I'll merge it in about 3 hours (at 6:30 PM in Paris)

**Comment by Felix-44** [comment]
wasnt this gonna get merged

**Comment by Volas171** [comment]
merging this pull request, completed

**Pull request merged**
